spring:
  datasource:
    url: jdbc:mysql://aws-sa-east-1.connect.psdb.cloud/booknook?sslMode=VERIFY_IDENTITY
    username: nyi8bj0ozy7st97wrafr
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver